# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/student/H-ESE-bathroomfan-pimvandermeer-655431

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/student/H-ESE-bathroomfan-pimvandermeer-655431

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/H-ESE-bathroomfan-pimvandermeer-655431/CMakeFiles /home/student/H-ESE-bathroomfan-pimvandermeer-655431/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/H-ESE-bathroomfan-pimvandermeer-655431/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named UnitTest

# Build rule for target.
UnitTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UnitTest
.PHONY : UnitTest

# fast build rule for target.
UnitTest/fast:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/build
.PHONY : UnitTest/fast

#=============================================================================
# Target rules for targets named bathroomfanprogram

# Build rule for target.
bathroomfanprogram: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bathroomfanprogram
.PHONY : bathroomfanprogram

# fast build rule for target.
bathroomfanprogram/fast:
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/build
.PHONY : bathroomfanprogram/fast

bathroomfan/calcbehaviour.o: bathroomfan/calcbehaviour.cpp.o

.PHONY : bathroomfan/calcbehaviour.o

# target to build an object file
bathroomfan/calcbehaviour.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/calcbehaviour.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/calcbehaviour.cpp.o
.PHONY : bathroomfan/calcbehaviour.cpp.o

bathroomfan/calcbehaviour.i: bathroomfan/calcbehaviour.cpp.i

.PHONY : bathroomfan/calcbehaviour.i

# target to preprocess a source file
bathroomfan/calcbehaviour.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/calcbehaviour.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/calcbehaviour.cpp.i
.PHONY : bathroomfan/calcbehaviour.cpp.i

bathroomfan/calcbehaviour.s: bathroomfan/calcbehaviour.cpp.s

.PHONY : bathroomfan/calcbehaviour.s

# target to generate assembly for a file
bathroomfan/calcbehaviour.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/calcbehaviour.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/calcbehaviour.cpp.s
.PHONY : bathroomfan/calcbehaviour.cpp.s

bathroomfan/errorfanstate.o: bathroomfan/errorfanstate.cpp.o

.PHONY : bathroomfan/errorfanstate.o

# target to build an object file
bathroomfan/errorfanstate.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/errorfanstate.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/errorfanstate.cpp.o
.PHONY : bathroomfan/errorfanstate.cpp.o

bathroomfan/errorfanstate.i: bathroomfan/errorfanstate.cpp.i

.PHONY : bathroomfan/errorfanstate.i

# target to preprocess a source file
bathroomfan/errorfanstate.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/errorfanstate.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/errorfanstate.cpp.i
.PHONY : bathroomfan/errorfanstate.cpp.i

bathroomfan/errorfanstate.s: bathroomfan/errorfanstate.cpp.s

.PHONY : bathroomfan/errorfanstate.s

# target to generate assembly for a file
bathroomfan/errorfanstate.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/errorfanstate.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/errorfanstate.cpp.s
.PHONY : bathroomfan/errorfanstate.cpp.s

bathroomfan/fancontext.o: bathroomfan/fancontext.cpp.o

.PHONY : bathroomfan/fancontext.o

# target to build an object file
bathroomfan/fancontext.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/fancontext.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/fancontext.cpp.o
.PHONY : bathroomfan/fancontext.cpp.o

bathroomfan/fancontext.i: bathroomfan/fancontext.cpp.i

.PHONY : bathroomfan/fancontext.i

# target to preprocess a source file
bathroomfan/fancontext.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/fancontext.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/fancontext.cpp.i
.PHONY : bathroomfan/fancontext.cpp.i

bathroomfan/fancontext.s: bathroomfan/fancontext.cpp.s

.PHONY : bathroomfan/fancontext.s

# target to generate assembly for a file
bathroomfan/fancontext.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/fancontext.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/fancontext.cpp.s
.PHONY : bathroomfan/fancontext.cpp.s

bathroomfan/fanstate.o: bathroomfan/fanstate.cpp.o

.PHONY : bathroomfan/fanstate.o

# target to build an object file
bathroomfan/fanstate.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/fanstate.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/fanstate.cpp.o
.PHONY : bathroomfan/fanstate.cpp.o

bathroomfan/fanstate.i: bathroomfan/fanstate.cpp.i

.PHONY : bathroomfan/fanstate.i

# target to preprocess a source file
bathroomfan/fanstate.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/fanstate.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/fanstate.cpp.i
.PHONY : bathroomfan/fanstate.cpp.i

bathroomfan/fanstate.s: bathroomfan/fanstate.cpp.s

.PHONY : bathroomfan/fanstate.s

# target to generate assembly for a file
bathroomfan/fanstate.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/fanstate.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/fanstate.cpp.s
.PHONY : bathroomfan/fanstate.cpp.s

bathroomfan/idlefanstate.o: bathroomfan/idlefanstate.cpp.o

.PHONY : bathroomfan/idlefanstate.o

# target to build an object file
bathroomfan/idlefanstate.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/idlefanstate.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/idlefanstate.cpp.o
.PHONY : bathroomfan/idlefanstate.cpp.o

bathroomfan/idlefanstate.i: bathroomfan/idlefanstate.cpp.i

.PHONY : bathroomfan/idlefanstate.i

# target to preprocess a source file
bathroomfan/idlefanstate.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/idlefanstate.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/idlefanstate.cpp.i
.PHONY : bathroomfan/idlefanstate.cpp.i

bathroomfan/idlefanstate.s: bathroomfan/idlefanstate.cpp.s

.PHONY : bathroomfan/idlefanstate.s

# target to generate assembly for a file
bathroomfan/idlefanstate.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/idlefanstate.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/idlefanstate.cpp.s
.PHONY : bathroomfan/idlefanstate.cpp.s

bathroomfan/initfanstate.o: bathroomfan/initfanstate.cpp.o

.PHONY : bathroomfan/initfanstate.o

# target to build an object file
bathroomfan/initfanstate.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/initfanstate.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/initfanstate.cpp.o
.PHONY : bathroomfan/initfanstate.cpp.o

bathroomfan/initfanstate.i: bathroomfan/initfanstate.cpp.i

.PHONY : bathroomfan/initfanstate.i

# target to preprocess a source file
bathroomfan/initfanstate.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/initfanstate.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/initfanstate.cpp.i
.PHONY : bathroomfan/initfanstate.cpp.i

bathroomfan/initfanstate.s: bathroomfan/initfanstate.cpp.s

.PHONY : bathroomfan/initfanstate.s

# target to generate assembly for a file
bathroomfan/initfanstate.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/initfanstate.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/initfanstate.cpp.s
.PHONY : bathroomfan/initfanstate.cpp.s

bathroomfan/logmanager.o: bathroomfan/logmanager.cpp.o

.PHONY : bathroomfan/logmanager.o

# target to build an object file
bathroomfan/logmanager.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/logmanager.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/logmanager.cpp.o
.PHONY : bathroomfan/logmanager.cpp.o

bathroomfan/logmanager.i: bathroomfan/logmanager.cpp.i

.PHONY : bathroomfan/logmanager.i

# target to preprocess a source file
bathroomfan/logmanager.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/logmanager.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/logmanager.cpp.i
.PHONY : bathroomfan/logmanager.cpp.i

bathroomfan/logmanager.s: bathroomfan/logmanager.cpp.s

.PHONY : bathroomfan/logmanager.s

# target to generate assembly for a file
bathroomfan/logmanager.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/logmanager.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/logmanager.cpp.s
.PHONY : bathroomfan/logmanager.cpp.s

bathroomfan/main.o: bathroomfan/main.cpp.o

.PHONY : bathroomfan/main.o

# target to build an object file
bathroomfan/main.cpp.o:
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/main.cpp.o
.PHONY : bathroomfan/main.cpp.o

bathroomfan/main.i: bathroomfan/main.cpp.i

.PHONY : bathroomfan/main.i

# target to preprocess a source file
bathroomfan/main.cpp.i:
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/main.cpp.i
.PHONY : bathroomfan/main.cpp.i

bathroomfan/main.s: bathroomfan/main.cpp.s

.PHONY : bathroomfan/main.s

# target to generate assembly for a file
bathroomfan/main.cpp.s:
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/main.cpp.s
.PHONY : bathroomfan/main.cpp.s

bathroomfan/relay.o: bathroomfan/relay.cpp.o

.PHONY : bathroomfan/relay.o

# target to build an object file
bathroomfan/relay.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/relay.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/relay.cpp.o
.PHONY : bathroomfan/relay.cpp.o

bathroomfan/relay.i: bathroomfan/relay.cpp.i

.PHONY : bathroomfan/relay.i

# target to preprocess a source file
bathroomfan/relay.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/relay.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/relay.cpp.i
.PHONY : bathroomfan/relay.cpp.i

bathroomfan/relay.s: bathroomfan/relay.cpp.s

.PHONY : bathroomfan/relay.s

# target to generate assembly for a file
bathroomfan/relay.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/relay.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/relay.cpp.s
.PHONY : bathroomfan/relay.cpp.s

bathroomfan/runfanstate.o: bathroomfan/runfanstate.cpp.o

.PHONY : bathroomfan/runfanstate.o

# target to build an object file
bathroomfan/runfanstate.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/runfanstate.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/runfanstate.cpp.o
.PHONY : bathroomfan/runfanstate.cpp.o

bathroomfan/runfanstate.i: bathroomfan/runfanstate.cpp.i

.PHONY : bathroomfan/runfanstate.i

# target to preprocess a source file
bathroomfan/runfanstate.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/runfanstate.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/runfanstate.cpp.i
.PHONY : bathroomfan/runfanstate.cpp.i

bathroomfan/runfanstate.s: bathroomfan/runfanstate.cpp.s

.PHONY : bathroomfan/runfanstate.s

# target to generate assembly for a file
bathroomfan/runfanstate.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/runfanstate.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/runfanstate.cpp.s
.PHONY : bathroomfan/runfanstate.cpp.s

bathroomfan/sensebehaviour.o: bathroomfan/sensebehaviour.cpp.o

.PHONY : bathroomfan/sensebehaviour.o

# target to build an object file
bathroomfan/sensebehaviour.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/sensebehaviour.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/sensebehaviour.cpp.o
.PHONY : bathroomfan/sensebehaviour.cpp.o

bathroomfan/sensebehaviour.i: bathroomfan/sensebehaviour.cpp.i

.PHONY : bathroomfan/sensebehaviour.i

# target to preprocess a source file
bathroomfan/sensebehaviour.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/sensebehaviour.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/sensebehaviour.cpp.i
.PHONY : bathroomfan/sensebehaviour.cpp.i

bathroomfan/sensebehaviour.s: bathroomfan/sensebehaviour.cpp.s

.PHONY : bathroomfan/sensebehaviour.s

# target to generate assembly for a file
bathroomfan/sensebehaviour.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/sensebehaviour.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/sensebehaviour.cpp.s
.PHONY : bathroomfan/sensebehaviour.cpp.s

bathroomfan/sensor.o: bathroomfan/sensor.cpp.o

.PHONY : bathroomfan/sensor.o

# target to build an object file
bathroomfan/sensor.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/sensor.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/sensor.cpp.o
.PHONY : bathroomfan/sensor.cpp.o

bathroomfan/sensor.i: bathroomfan/sensor.cpp.i

.PHONY : bathroomfan/sensor.i

# target to preprocess a source file
bathroomfan/sensor.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/sensor.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/sensor.cpp.i
.PHONY : bathroomfan/sensor.cpp.i

bathroomfan/sensor.s: bathroomfan/sensor.cpp.s

.PHONY : bathroomfan/sensor.s

# target to generate assembly for a file
bathroomfan/sensor.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/sensor.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/sensor.cpp.s
.PHONY : bathroomfan/sensor.cpp.s

bathroomfan/timer.o: bathroomfan/timer.cpp.o

.PHONY : bathroomfan/timer.o

# target to build an object file
bathroomfan/timer.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/timer.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/timer.cpp.o
.PHONY : bathroomfan/timer.cpp.o

bathroomfan/timer.i: bathroomfan/timer.cpp.i

.PHONY : bathroomfan/timer.i

# target to preprocess a source file
bathroomfan/timer.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/timer.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/timer.cpp.i
.PHONY : bathroomfan/timer.cpp.i

bathroomfan/timer.s: bathroomfan/timer.cpp.s

.PHONY : bathroomfan/timer.s

# target to generate assembly for a file
bathroomfan/timer.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/bathroomfan/timer.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfanprogram.dir/build.make CMakeFiles/bathroomfanprogram.dir/bathroomfan/timer.cpp.s
.PHONY : bathroomfan/timer.cpp.s

test/context_test.o: test/context_test.cpp.o

.PHONY : test/context_test.o

# target to build an object file
test/context_test.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/context_test.cpp.o
.PHONY : test/context_test.cpp.o

test/context_test.i: test/context_test.cpp.i

.PHONY : test/context_test.i

# target to preprocess a source file
test/context_test.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/context_test.cpp.i
.PHONY : test/context_test.cpp.i

test/context_test.s: test/context_test.cpp.s

.PHONY : test/context_test.s

# target to generate assembly for a file
test/context_test.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/context_test.cpp.s
.PHONY : test/context_test.cpp.s

test/log_test.o: test/log_test.cpp.o

.PHONY : test/log_test.o

# target to build an object file
test/log_test.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/log_test.cpp.o
.PHONY : test/log_test.cpp.o

test/log_test.i: test/log_test.cpp.i

.PHONY : test/log_test.i

# target to preprocess a source file
test/log_test.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/log_test.cpp.i
.PHONY : test/log_test.cpp.i

test/log_test.s: test/log_test.cpp.s

.PHONY : test/log_test.s

# target to generate assembly for a file
test/log_test.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/log_test.cpp.s
.PHONY : test/log_test.cpp.s

test/main.o: test/main.cpp.o

.PHONY : test/main.o

# target to build an object file
test/main.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/main.cpp.o
.PHONY : test/main.cpp.o

test/main.i: test/main.cpp.i

.PHONY : test/main.i

# target to preprocess a source file
test/main.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/main.cpp.i
.PHONY : test/main.cpp.i

test/main.s: test/main.cpp.s

.PHONY : test/main.s

# target to generate assembly for a file
test/main.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/main.cpp.s
.PHONY : test/main.cpp.s

test/relay_test.o: test/relay_test.cpp.o

.PHONY : test/relay_test.o

# target to build an object file
test/relay_test.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/relay_test.cpp.o
.PHONY : test/relay_test.cpp.o

test/relay_test.i: test/relay_test.cpp.i

.PHONY : test/relay_test.i

# target to preprocess a source file
test/relay_test.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/relay_test.cpp.i
.PHONY : test/relay_test.cpp.i

test/relay_test.s: test/relay_test.cpp.s

.PHONY : test/relay_test.s

# target to generate assembly for a file
test/relay_test.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/relay_test.cpp.s
.PHONY : test/relay_test.cpp.s

test/sensor_test.o: test/sensor_test.cpp.o

.PHONY : test/sensor_test.o

# target to build an object file
test/sensor_test.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/sensor_test.cpp.o
.PHONY : test/sensor_test.cpp.o

test/sensor_test.i: test/sensor_test.cpp.i

.PHONY : test/sensor_test.i

# target to preprocess a source file
test/sensor_test.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/sensor_test.cpp.i
.PHONY : test/sensor_test.cpp.i

test/sensor_test.s: test/sensor_test.cpp.s

.PHONY : test/sensor_test.s

# target to generate assembly for a file
test/sensor_test.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/sensor_test.cpp.s
.PHONY : test/sensor_test.cpp.s

test/state_test.o: test/state_test.cpp.o

.PHONY : test/state_test.o

# target to build an object file
test/state_test.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/state_test.cpp.o
.PHONY : test/state_test.cpp.o

test/state_test.i: test/state_test.cpp.i

.PHONY : test/state_test.i

# target to preprocess a source file
test/state_test.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/state_test.cpp.i
.PHONY : test/state_test.cpp.i

test/state_test.s: test/state_test.cpp.s

.PHONY : test/state_test.s

# target to generate assembly for a file
test/state_test.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/state_test.cpp.s
.PHONY : test/state_test.cpp.s

test/timer_test.o: test/timer_test.cpp.o

.PHONY : test/timer_test.o

# target to build an object file
test/timer_test.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/timer_test.cpp.o
.PHONY : test/timer_test.cpp.o

test/timer_test.i: test/timer_test.cpp.i

.PHONY : test/timer_test.i

# target to preprocess a source file
test/timer_test.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/timer_test.cpp.i
.PHONY : test/timer_test.cpp.i

test/timer_test.s: test/timer_test.cpp.s

.PHONY : test/timer_test.s

# target to generate assembly for a file
test/timer_test.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/timer_test.cpp.s
.PHONY : test/timer_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... UnitTest"
	@echo "... bathroomfanprogram"
	@echo "... bathroomfan/calcbehaviour.o"
	@echo "... bathroomfan/calcbehaviour.i"
	@echo "... bathroomfan/calcbehaviour.s"
	@echo "... bathroomfan/errorfanstate.o"
	@echo "... bathroomfan/errorfanstate.i"
	@echo "... bathroomfan/errorfanstate.s"
	@echo "... bathroomfan/fancontext.o"
	@echo "... bathroomfan/fancontext.i"
	@echo "... bathroomfan/fancontext.s"
	@echo "... bathroomfan/fanstate.o"
	@echo "... bathroomfan/fanstate.i"
	@echo "... bathroomfan/fanstate.s"
	@echo "... bathroomfan/idlefanstate.o"
	@echo "... bathroomfan/idlefanstate.i"
	@echo "... bathroomfan/idlefanstate.s"
	@echo "... bathroomfan/initfanstate.o"
	@echo "... bathroomfan/initfanstate.i"
	@echo "... bathroomfan/initfanstate.s"
	@echo "... bathroomfan/logmanager.o"
	@echo "... bathroomfan/logmanager.i"
	@echo "... bathroomfan/logmanager.s"
	@echo "... bathroomfan/main.o"
	@echo "... bathroomfan/main.i"
	@echo "... bathroomfan/main.s"
	@echo "... bathroomfan/relay.o"
	@echo "... bathroomfan/relay.i"
	@echo "... bathroomfan/relay.s"
	@echo "... bathroomfan/runfanstate.o"
	@echo "... bathroomfan/runfanstate.i"
	@echo "... bathroomfan/runfanstate.s"
	@echo "... bathroomfan/sensebehaviour.o"
	@echo "... bathroomfan/sensebehaviour.i"
	@echo "... bathroomfan/sensebehaviour.s"
	@echo "... bathroomfan/sensor.o"
	@echo "... bathroomfan/sensor.i"
	@echo "... bathroomfan/sensor.s"
	@echo "... bathroomfan/timer.o"
	@echo "... bathroomfan/timer.i"
	@echo "... bathroomfan/timer.s"
	@echo "... test/context_test.o"
	@echo "... test/context_test.i"
	@echo "... test/context_test.s"
	@echo "... test/log_test.o"
	@echo "... test/log_test.i"
	@echo "... test/log_test.s"
	@echo "... test/main.o"
	@echo "... test/main.i"
	@echo "... test/main.s"
	@echo "... test/relay_test.o"
	@echo "... test/relay_test.i"
	@echo "... test/relay_test.s"
	@echo "... test/sensor_test.o"
	@echo "... test/sensor_test.i"
	@echo "... test/sensor_test.s"
	@echo "... test/state_test.o"
	@echo "... test/state_test.i"
	@echo "... test/state_test.s"
	@echo "... test/timer_test.o"
	@echo "... test/timer_test.i"
	@echo "... test/timer_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

