# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/student/BathRoomFan/bathroomfancmake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/student/BathRoomFan

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/BathRoomFan/CMakeFiles /home/student/BathRoomFan/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/BathRoomFan/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named UnitTest

# Build rule for target.
UnitTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UnitTest
.PHONY : UnitTest

# fast build rule for target.
UnitTest/fast:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/build
.PHONY : UnitTest/fast

#=============================================================================
# Target rules for targets named bathroomfan

# Build rule for target.
bathroomfan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bathroomfan
.PHONY : bathroomfan

# fast build rule for target.
bathroomfan/fast:
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/build
.PHONY : bathroomfan/fast

calcbehaviour.o: calcbehaviour.cpp.o

.PHONY : calcbehaviour.o

# target to build an object file
calcbehaviour.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/calcbehaviour.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/calcbehaviour.cpp.o
.PHONY : calcbehaviour.cpp.o

calcbehaviour.i: calcbehaviour.cpp.i

.PHONY : calcbehaviour.i

# target to preprocess a source file
calcbehaviour.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/calcbehaviour.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/calcbehaviour.cpp.i
.PHONY : calcbehaviour.cpp.i

calcbehaviour.s: calcbehaviour.cpp.s

.PHONY : calcbehaviour.s

# target to generate assembly for a file
calcbehaviour.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/calcbehaviour.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/calcbehaviour.cpp.s
.PHONY : calcbehaviour.cpp.s

errorfanstate.o: errorfanstate.cpp.o

.PHONY : errorfanstate.o

# target to build an object file
errorfanstate.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/errorfanstate.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/errorfanstate.cpp.o
.PHONY : errorfanstate.cpp.o

errorfanstate.i: errorfanstate.cpp.i

.PHONY : errorfanstate.i

# target to preprocess a source file
errorfanstate.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/errorfanstate.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/errorfanstate.cpp.i
.PHONY : errorfanstate.cpp.i

errorfanstate.s: errorfanstate.cpp.s

.PHONY : errorfanstate.s

# target to generate assembly for a file
errorfanstate.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/errorfanstate.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/errorfanstate.cpp.s
.PHONY : errorfanstate.cpp.s

fancontext.o: fancontext.cpp.o

.PHONY : fancontext.o

# target to build an object file
fancontext.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/fancontext.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/fancontext.cpp.o
.PHONY : fancontext.cpp.o

fancontext.i: fancontext.cpp.i

.PHONY : fancontext.i

# target to preprocess a source file
fancontext.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/fancontext.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/fancontext.cpp.i
.PHONY : fancontext.cpp.i

fancontext.s: fancontext.cpp.s

.PHONY : fancontext.s

# target to generate assembly for a file
fancontext.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/fancontext.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/fancontext.cpp.s
.PHONY : fancontext.cpp.s

fanstate.o: fanstate.cpp.o

.PHONY : fanstate.o

# target to build an object file
fanstate.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/fanstate.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/fanstate.cpp.o
.PHONY : fanstate.cpp.o

fanstate.i: fanstate.cpp.i

.PHONY : fanstate.i

# target to preprocess a source file
fanstate.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/fanstate.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/fanstate.cpp.i
.PHONY : fanstate.cpp.i

fanstate.s: fanstate.cpp.s

.PHONY : fanstate.s

# target to generate assembly for a file
fanstate.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/fanstate.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/fanstate.cpp.s
.PHONY : fanstate.cpp.s

idlefanstate.o: idlefanstate.cpp.o

.PHONY : idlefanstate.o

# target to build an object file
idlefanstate.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/idlefanstate.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/idlefanstate.cpp.o
.PHONY : idlefanstate.cpp.o

idlefanstate.i: idlefanstate.cpp.i

.PHONY : idlefanstate.i

# target to preprocess a source file
idlefanstate.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/idlefanstate.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/idlefanstate.cpp.i
.PHONY : idlefanstate.cpp.i

idlefanstate.s: idlefanstate.cpp.s

.PHONY : idlefanstate.s

# target to generate assembly for a file
idlefanstate.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/idlefanstate.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/idlefanstate.cpp.s
.PHONY : idlefanstate.cpp.s

initfanstate.o: initfanstate.cpp.o

.PHONY : initfanstate.o

# target to build an object file
initfanstate.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/initfanstate.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/initfanstate.cpp.o
.PHONY : initfanstate.cpp.o

initfanstate.i: initfanstate.cpp.i

.PHONY : initfanstate.i

# target to preprocess a source file
initfanstate.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/initfanstate.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/initfanstate.cpp.i
.PHONY : initfanstate.cpp.i

initfanstate.s: initfanstate.cpp.s

.PHONY : initfanstate.s

# target to generate assembly for a file
initfanstate.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/initfanstate.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/initfanstate.cpp.s
.PHONY : initfanstate.cpp.s

logmanager.o: logmanager.cpp.o

.PHONY : logmanager.o

# target to build an object file
logmanager.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/logmanager.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/logmanager.cpp.o
.PHONY : logmanager.cpp.o

logmanager.i: logmanager.cpp.i

.PHONY : logmanager.i

# target to preprocess a source file
logmanager.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/logmanager.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/logmanager.cpp.i
.PHONY : logmanager.cpp.i

logmanager.s: logmanager.cpp.s

.PHONY : logmanager.s

# target to generate assembly for a file
logmanager.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/logmanager.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/logmanager.cpp.s
.PHONY : logmanager.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/main.cpp.s
.PHONY : main.cpp.s

relay.o: relay.cpp.o

.PHONY : relay.o

# target to build an object file
relay.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/relay.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/relay.cpp.o
.PHONY : relay.cpp.o

relay.i: relay.cpp.i

.PHONY : relay.i

# target to preprocess a source file
relay.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/relay.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/relay.cpp.i
.PHONY : relay.cpp.i

relay.s: relay.cpp.s

.PHONY : relay.s

# target to generate assembly for a file
relay.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/relay.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/relay.cpp.s
.PHONY : relay.cpp.s

runfanstate.o: runfanstate.cpp.o

.PHONY : runfanstate.o

# target to build an object file
runfanstate.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/runfanstate.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/runfanstate.cpp.o
.PHONY : runfanstate.cpp.o

runfanstate.i: runfanstate.cpp.i

.PHONY : runfanstate.i

# target to preprocess a source file
runfanstate.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/runfanstate.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/runfanstate.cpp.i
.PHONY : runfanstate.cpp.i

runfanstate.s: runfanstate.cpp.s

.PHONY : runfanstate.s

# target to generate assembly for a file
runfanstate.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/runfanstate.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/runfanstate.cpp.s
.PHONY : runfanstate.cpp.s

sensebehaviour.o: sensebehaviour.cpp.o

.PHONY : sensebehaviour.o

# target to build an object file
sensebehaviour.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/sensebehaviour.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/sensebehaviour.cpp.o
.PHONY : sensebehaviour.cpp.o

sensebehaviour.i: sensebehaviour.cpp.i

.PHONY : sensebehaviour.i

# target to preprocess a source file
sensebehaviour.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/sensebehaviour.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/sensebehaviour.cpp.i
.PHONY : sensebehaviour.cpp.i

sensebehaviour.s: sensebehaviour.cpp.s

.PHONY : sensebehaviour.s

# target to generate assembly for a file
sensebehaviour.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/sensebehaviour.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/sensebehaviour.cpp.s
.PHONY : sensebehaviour.cpp.s

sensor.o: sensor.cpp.o

.PHONY : sensor.o

# target to build an object file
sensor.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/sensor.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/sensor.cpp.o
.PHONY : sensor.cpp.o

sensor.i: sensor.cpp.i

.PHONY : sensor.i

# target to preprocess a source file
sensor.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/sensor.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/sensor.cpp.i
.PHONY : sensor.cpp.i

sensor.s: sensor.cpp.s

.PHONY : sensor.s

# target to generate assembly for a file
sensor.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/sensor.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/sensor.cpp.s
.PHONY : sensor.cpp.s

test/context_test.o: test/context_test.cpp.o

.PHONY : test/context_test.o

# target to build an object file
test/context_test.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/context_test.cpp.o
.PHONY : test/context_test.cpp.o

test/context_test.i: test/context_test.cpp.i

.PHONY : test/context_test.i

# target to preprocess a source file
test/context_test.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/context_test.cpp.i
.PHONY : test/context_test.cpp.i

test/context_test.s: test/context_test.cpp.s

.PHONY : test/context_test.s

# target to generate assembly for a file
test/context_test.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/context_test.cpp.s
.PHONY : test/context_test.cpp.s

test/log_test.o: test/log_test.cpp.o

.PHONY : test/log_test.o

# target to build an object file
test/log_test.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/log_test.cpp.o
.PHONY : test/log_test.cpp.o

test/log_test.i: test/log_test.cpp.i

.PHONY : test/log_test.i

# target to preprocess a source file
test/log_test.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/log_test.cpp.i
.PHONY : test/log_test.cpp.i

test/log_test.s: test/log_test.cpp.s

.PHONY : test/log_test.s

# target to generate assembly for a file
test/log_test.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/log_test.cpp.s
.PHONY : test/log_test.cpp.s

test/main.o: test/main.cpp.o

.PHONY : test/main.o

# target to build an object file
test/main.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/main.cpp.o
.PHONY : test/main.cpp.o

test/main.i: test/main.cpp.i

.PHONY : test/main.i

# target to preprocess a source file
test/main.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/main.cpp.i
.PHONY : test/main.cpp.i

test/main.s: test/main.cpp.s

.PHONY : test/main.s

# target to generate assembly for a file
test/main.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/main.cpp.s
.PHONY : test/main.cpp.s

test/relay_test.o: test/relay_test.cpp.o

.PHONY : test/relay_test.o

# target to build an object file
test/relay_test.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/relay_test.cpp.o
.PHONY : test/relay_test.cpp.o

test/relay_test.i: test/relay_test.cpp.i

.PHONY : test/relay_test.i

# target to preprocess a source file
test/relay_test.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/relay_test.cpp.i
.PHONY : test/relay_test.cpp.i

test/relay_test.s: test/relay_test.cpp.s

.PHONY : test/relay_test.s

# target to generate assembly for a file
test/relay_test.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/relay_test.cpp.s
.PHONY : test/relay_test.cpp.s

test/sensor_test.o: test/sensor_test.cpp.o

.PHONY : test/sensor_test.o

# target to build an object file
test/sensor_test.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/sensor_test.cpp.o
.PHONY : test/sensor_test.cpp.o

test/sensor_test.i: test/sensor_test.cpp.i

.PHONY : test/sensor_test.i

# target to preprocess a source file
test/sensor_test.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/sensor_test.cpp.i
.PHONY : test/sensor_test.cpp.i

test/sensor_test.s: test/sensor_test.cpp.s

.PHONY : test/sensor_test.s

# target to generate assembly for a file
test/sensor_test.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/sensor_test.cpp.s
.PHONY : test/sensor_test.cpp.s

test/state_test.o: test/state_test.cpp.o

.PHONY : test/state_test.o

# target to build an object file
test/state_test.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/state_test.cpp.o
.PHONY : test/state_test.cpp.o

test/state_test.i: test/state_test.cpp.i

.PHONY : test/state_test.i

# target to preprocess a source file
test/state_test.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/state_test.cpp.i
.PHONY : test/state_test.cpp.i

test/state_test.s: test/state_test.cpp.s

.PHONY : test/state_test.s

# target to generate assembly for a file
test/state_test.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/state_test.cpp.s
.PHONY : test/state_test.cpp.s

test/timer_test.o: test/timer_test.cpp.o

.PHONY : test/timer_test.o

# target to build an object file
test/timer_test.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/timer_test.cpp.o
.PHONY : test/timer_test.cpp.o

test/timer_test.i: test/timer_test.cpp.i

.PHONY : test/timer_test.i

# target to preprocess a source file
test/timer_test.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/timer_test.cpp.i
.PHONY : test/timer_test.cpp.i

test/timer_test.s: test/timer_test.cpp.s

.PHONY : test/timer_test.s

# target to generate assembly for a file
test/timer_test.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/test/timer_test.cpp.s
.PHONY : test/timer_test.cpp.s

timer.o: timer.cpp.o

.PHONY : timer.o

# target to build an object file
timer.cpp.o:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/timer.cpp.o
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/timer.cpp.o
.PHONY : timer.cpp.o

timer.i: timer.cpp.i

.PHONY : timer.i

# target to preprocess a source file
timer.cpp.i:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/timer.cpp.i
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/timer.cpp.i
.PHONY : timer.cpp.i

timer.s: timer.cpp.s

.PHONY : timer.s

# target to generate assembly for a file
timer.cpp.s:
	$(MAKE) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/timer.cpp.s
	$(MAKE) -f CMakeFiles/bathroomfan.dir/build.make CMakeFiles/bathroomfan.dir/timer.cpp.s
.PHONY : timer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... UnitTest"
	@echo "... bathroomfan"
	@echo "... calcbehaviour.o"
	@echo "... calcbehaviour.i"
	@echo "... calcbehaviour.s"
	@echo "... errorfanstate.o"
	@echo "... errorfanstate.i"
	@echo "... errorfanstate.s"
	@echo "... fancontext.o"
	@echo "... fancontext.i"
	@echo "... fancontext.s"
	@echo "... fanstate.o"
	@echo "... fanstate.i"
	@echo "... fanstate.s"
	@echo "... idlefanstate.o"
	@echo "... idlefanstate.i"
	@echo "... idlefanstate.s"
	@echo "... initfanstate.o"
	@echo "... initfanstate.i"
	@echo "... initfanstate.s"
	@echo "... logmanager.o"
	@echo "... logmanager.i"
	@echo "... logmanager.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... relay.o"
	@echo "... relay.i"
	@echo "... relay.s"
	@echo "... runfanstate.o"
	@echo "... runfanstate.i"
	@echo "... runfanstate.s"
	@echo "... sensebehaviour.o"
	@echo "... sensebehaviour.i"
	@echo "... sensebehaviour.s"
	@echo "... sensor.o"
	@echo "... sensor.i"
	@echo "... sensor.s"
	@echo "... test/context_test.o"
	@echo "... test/context_test.i"
	@echo "... test/context_test.s"
	@echo "... test/log_test.o"
	@echo "... test/log_test.i"
	@echo "... test/log_test.s"
	@echo "... test/main.o"
	@echo "... test/main.i"
	@echo "... test/main.s"
	@echo "... test/relay_test.o"
	@echo "... test/relay_test.i"
	@echo "... test/relay_test.s"
	@echo "... test/sensor_test.o"
	@echo "... test/sensor_test.i"
	@echo "... test/sensor_test.s"
	@echo "... test/state_test.o"
	@echo "... test/state_test.i"
	@echo "... test/state_test.s"
	@echo "... test/timer_test.o"
	@echo "... test/timer_test.i"
	@echo "... test/timer_test.s"
	@echo "... timer.o"
	@echo "... timer.i"
	@echo "... timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

